### ISSUE TITLE
전화번호 표시 부분(contactDiv)

### ISSUE THREAD

**Issue by suho-han** [amuguna1mandeum/lockerweb#15]
![image](https://user-images.githubusercontent.com/58286965/144741027-c083a61d-0b43-4813-88ca-0d31c4e8a68b.png)
@makemyway-kr 별 문제 없는데??

**Comment by makemyway-kr** [comment]
뭔가 저 아래에 내려와있는게 맘에 안든다는거였음 문제가 아니라 ㅋㅅㅋ

**Comment by suho-han** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 그런 말이였구나
아무 생각 없이 길게 한 건데 팝업으로 뜨게 할까

**Comment by makemyway-kr** [comment]
팝업 낫뱃
