### ISSUE TITLE
남은 자리수 표시가 안뜸...😭

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/lockerweb#17]
![image](https://user-images.githubusercontent.com/58161987/144776841-e88516a9-2e68-4a88-89c3-ae3edd20ae3a.png)
디비에 사물함 잘 넣었는데도 이런다....

**Comment by makemyway-kr** [comment]
shell에서는 잘 뜨는데 template으로 안넘어간다...
@unbroken2650

**Comment by suho-han** [comment]
ㅋㅋㅋㅋ뭐지

**Comment by makemyway-kr** [comment]
뜬다!~~ loginviewasview때문에 views.py의 index함수를 안거치고 랜더링 되고 있는게 문제였음
