### ISSUE TITLE
버튼 다 깨지는 현상 발생

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/lockerweb#24]
![image](https://user-images.githubusercontent.com/58161987/147099019-bea96b96-180b-4d23-b8ad-b3608860ff83.png)

**Comment by suho-han** [comment]
코드에 이상 없음.
오늘 저녁에 다시 볼게

**Comment by makemyway-kr** [comment]
@unbroken2650 확인해봤음?

**Comment by suho-han** [comment]
> @unbroken2650 확인해봤음?

오늘 볼게 ㅋㅋ..아직도 그래?

**Comment by suho-han** [comment]
![image](https://user-images.githubusercontent.com/58286965/147355245-204007d6-9e9a-4ca9-a6c4-2bb2cb9bcbb2.png)
난 잘 뜨는데..?

**Comment by suho-han** [comment]
![image](https://user-images.githubusercontent.com/58286965/147355292-43d86180-84f4-467b-9b6e-f34febe17b56.png)
원래 repo 클론해서 해봐도 잘 뜸..

**Comment by makemyway-kr** [comment]
나도 맥북이랑 ec2에서는 잘 되는데 데탑만 저럼

**Comment by suho-han** [comment]
그럼 모르겠다..?
