### ISSUE TITLE
로그인을 해야 들어갈 수 있게 변경 필요

### ISSUE THREAD

**Issue by suho-han** [amuguna1mandeum/lockerweb#27]
locker/reserve, locker/cancel 페이지가 로그인 없이도 들어갈 수 있음.
lockerlist처럼 로그인을 해야 들어갈 수 있게 하면 될듯.

**Comment by makemyway-kr** [comment]
locker/reserve , cancel은 페이지가 아니라 api url인데..?일단 그렇게 해놓을께

**Comment by makemyway-kr** [comment]
아 하긴 보안에 안좋기는 하다

**Comment by suho-han** [comment]
다른 html 페이지로 들어가는 거라 똑같이 해두면 좋을 거 같아서

**Comment by makemyway-kr** [comment]
완료
