### ISSUE TITLE
예약하기 버튼 클릭시, 500 server error 발생

### ISSUE THREAD

**Issue by intersoom** [amuguna1mandeum/lockerweb#31]
<img width="765" alt="스크린샷 2022-01-03 오전 1 22 54" src="https://user-images.githubusercontent.com/78731710/147882256-b1e6f5c8-1990-4805-b1ba-70ff4577ad13.png">

이렇게 요청을 보냈는데

<img width="1440" alt="스크린샷 2022-01-03 오전 1 24 21" src="https://user-images.githubusercontent.com/78731710/147882276-6f4818a8-668b-457d-a549-944588b984cd.png">

요렇게 에러 창이 뜨네용!
찾아보니까 인코딩 문제라고 하는 것 같아서 한 번 확인 부탁드립니당!
요청 보낼 때 문제일 수도 있으니까 저도 찾아볼게요!

@makemyway-kr

**Comment by makemyway-kr** [comment]
앗 오케이~!
