### ISSUE TITLE
static file(CSS, SASS, ...) settings

### ISSUE THREAD

**Issue by suho-han** [amuguna1mandeum/lockerweb#4]
[http://pythonstudy.xyz/python/article/314-Static-%ED%8C%8C%EC%9D%BC](http://pythonstudy.xyz/python/article/314-Static-%ED%8C%8C%EC%9D%BC)

ssulocker > static 폴더에 CSS 파일 넣을거야

링크에서 1번처럼 해도 되고, 전에 해봤는데 4번으로 그냥 모아놓고 쓰게 만들어도 되고 상관없을듯

**Comment by makemyway-kr** [comment]
모아 놓고 쓰는게 재활용하고 좋지않을까싶은데

**Comment by suho-han** [comment]
ㅇㅋㅇㅋ 내가 만든 건 static에 넣어둘테니까 모아서 쓰셈
짜피 실행은 너가 하니까

**Comment by makemyway-kr** [comment]
오케이~
