### ISSUE TITLE
OperationalError

### ISSUE THREAD

**Issue by suho-han** [amuguna1mandeum/lockerweb#42]
![image](https://user-images.githubusercontent.com/58286965/148640170-eddb283b-a1f7-407c-9089-e57100e582e2.png)
DB가 없어서 그런가?

**Comment by suho-han** [comment]
![image](https://user-images.githubusercontent.com/58286965/148640238-a393d006-5939-4e8a-87a8-fd3ed99a66c1.png)
settings.py 는 이렇게 바꿈

**Comment by makemyway-kr** [comment]
@unbroken2650 sqlitedb가 지금 디비 변경사항이 적용이안돼서그래
sqlite에다가 python3 manage.py migrate 해봐

**Comment by makemyway-kr** [comment]
수호야 네 오류는 그 sqlite디비에 지금 장고에서 변경된 사항이 적용이안되어있어서 그러니까
python3 manage.py migrate명령어 쳐보고
 물론 manage.py 있는 디렉토리에서 이 명령어 실행시켜야하고
 만약에 오류뜨면
sqlite파일 지우고
https://softwaree.tistory.com/79
 요거를 따라한 뒤에
사물함 정보를 csv파일에서 다시 옮기렴

**Comment by makemyway-kr** [comment]
> ![image](https://user-images.githubusercontent.com/58286965/148640170-eddb283b-a1f7-407c-9089-e57100e582e2.png) DB가 없어서 그런가?

수호야 네 오류는 그 sqlite디비에 지금 장고에서 변경된 사항이 적용이안되어있어서 그러니까
python3 manage.py migrate명령어 쳐보고
물론 manage.py 있는 디렉토리에서 이 명령어 실행시켜야하고
만약에 오류뜨면
sqlite파일 지우고
https://softwaree.tistory.com/79
요거를 따라한 뒤에
사물함 정보를 csv파일에서 다시 옮기렴

**Comment by suho-han** [comment]
똑같이 했음 그래도 뜨네
