### ISSUE TITLE
DOCKER image의 필요성

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/lockerweb#44]
서버를 학생회 서버로 이전할 때에, requirements가 있다해도 docker를 사용해서 지금 EC2에 설치된 것들 + app을 image화 해주는게 훨씬 편할듯 함. 해당 작업 진행 예정.

**Comment by makemyway-kr** [comment]
env image는 hub에 올렸음. AWS에서 AMI이용해서 한번에 옮기는것도 방법인데 AWS가 아닌 다른 서버면 이건 좀 문제

**Comment by suho-han** [comment]
docker가 협업할 때도 같은 작업환경으로 할 수 있어서 좋은거였나. 한번도 안 써봐서 모르겠다. 좋을듯.

**Comment by makemyway-kr** [comment]
협업할 때 환경설정 일정하게 맞춰줄 수도 있고 서버에 올릴때 이미지만 있으면 똑같이 다른 서버에 올릴 수 있어서 그럼
@unbroken2650

**Comment by suho-han** [comment]
> 협업할 때 환경설정 일정하게 맞춰줄 수도 있고 서버에 올릴때 이미지만 있으면 똑같이 다른 서버에 올릴 수 있어서 그럼 @unbroken2650

나도 차차 공부해서 다음에 써보지 뭐.
