### ISSUE TITLE
OperationError 2

### ISSUE THREAD

**Issue by unbroken2650** [amuguna1mandeum/lockerweb#51]
![image](https://user-images.githubusercontent.com/58286965/150350159-c6c5b8e2-47bd-42bb-a0ab-68063b514a75.png)

넌 실행 잘 되는데 나는 안 되는 거면 sqlite 가 안 되는거지?

**Comment by suho-han** [comment]
아닌가 너가 이거 메서드 오류였다며
![image](https://user-images.githubusercontent.com/58286965/150350300-2552555a-d3cd-495e-b46f-470c86fef1a7.png)

**Comment by makemyway-kr** [comment]
> 아닌가 너가 이거 메서드 오류였다며
> ![image](https://user-images.githubusercontent.com/58286965/150350300-2552555a-d3cd-495e-b46f-470c86fef1a7.png)

Sqlite에서 나도 해봤는데 잘됐었음

**Comment by suho-han** [comment]
싹 다 다시 세팅하니까 됐다... 클라우드 환경 개같네..
잘 된다 내일부터 디자인할게 bb

**Comment by makemyway-kr** [comment]
> 싹 다 다시 세팅하니까 됐다... 클라우드 환경 개같네..
> 잘 된다 내일부터 디자인할게 bb

굿
