### ISSUE TITLE
passwordchange 오류

### ISSUE THREAD

**Issue by suho-han** [amuguna1mandeum/lockerweb#55]
Branch : main
#50 
- 비밀번호 변경 시 새 비밀번호와 새 비밀번호(확인)이 달라도 페이지가 넘어가짐.
- 비밀번호 변경 화면에서 로그인 불가 시 경고 문구 뜨지 않음.
- 비밀번호 변경 화면에서 홈화면으로 돌아가는 방법 없음.(직접 추가 예정)
- 비밀번호 변경 안 됨(???)

계속 테스트해보는데 비밀번호 변경이 안 되네요

**Comment by makemyway-kr** [comment]
내가 테스트했을때 잘 되던디

2022년 1월 22일 (토) 오후 9:59, UnbroKen ***@***.***>님이 작성:

**Comment by makemyway-kr** [comment]
sqlite로 한겨?

**Comment by suho-han** [comment]
> sqlite로 한겨?

ㅇㅇ..그거 문제인가
1, 2번 잘 돼?

**Comment by makemyway-kr** [comment]
비밀번호 변경은 내가 어드민 계정 비번 바꾸고 바꾼 비번으로 로그인 되는걸로 봐서는 잘 되는거 같고 2번은 추가해젔어 오류문구.
1번은 함 테스트 해봐야할듯

**Comment by suho-han** [comment]
오케이 확인부탁.

**Comment by suho-han** [comment]
이거 1, 2번은 테스트 해봤나?

**Comment by makemyway-kr** [comment]
테스트및 수정 완료
