### ISSUE TITLE
pwchangeForm 요소들 위치 바꾸는 방법 모르겠음.

### ISSUE THREAD

**Issue by suho-han** [amuguna1mandeum/lockerweb#58]
![image](https://user-images.githubusercontent.com/58286965/150640482-d7c0604e-9ce8-42cb-8cdb-cfccc76ead38.png)
![image](https://user-images.githubusercontent.com/58286965/150640486-0298096d-d6b0-490f-906c-862b6edbe5e0.png)
어떻게 바꾸나요? @makemyway-kr

**Comment by makemyway-kr** [comment]
이거 찾아보니까 {{form}}를 뭐 <div></div>로 감싸든 해서 style먹이면 될거같은데?

**Comment by suho-han** [comment]
그건 알겠는데 일부러 새 비밀번호랑 확인 사이에 규칙 넣은거 맞아?
기존-규칙-신규-신규(확인)
이게 낫지않나

**Comment by makemyway-kr** [comment]
그거 기본제공 form이라서 내가 못고쳐 ㅋㅋㅋㅋ

**Comment by suho-han** [comment]
그럼 그냥 로그인 폼처럼 바꾸면 안 돼??
어디서 가져온거야?

**Comment by makemyway-kr** [comment]
장고 기본 제공 폼인데 일단 베타때는 저거 쓰고 중요한건 아니니까 나중에 고치면 어떨까?

**Comment by suho-han** [comment]
ㅋㅋㅋㅋㅋㅋ 오케 너무 불편..

일단 로그인 폼 디자인 긁어서 저래 뒀음

**Comment by makemyway-kr** [comment]
굿 👍

2022년 1월 22일 (토) 오후 11:50, UnbroKen ***@***.***>님이 작성:
