### ISSUE TITLE
학생 excel로 가져오고 정보 다시 엑셀로 내보내고 / 비밀번호 초기화 하는것 완료

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/lockerweb#59]
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/58161987/150642318-2ace9088-41a4-4303-9cbd-f87337d712e8.png">

전화번호는 010떼고 엑셀에 적어놓도록 해야할듯.

**Comment by suho-han** [comment]
> 전화번호는 010떼고 엑셀에 적어놓도록 해야할듯.

처음부터 학생회에서 정보 넣을 때 그렇게 하라고 메뉴얼에 추가해야 함.

**Comment by makemyway-kr** [comment]
ㅇㅇ 메뉴얼 만들때 추가하려고
