### ISSUE TITLE
테스트 디비에서 예약 안되는 현상발생.

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/lockerweb#63]
원래 디비에서는 예약이 잘 되는데 테스트용에서는 되지 않음...뭐지

**Comment by makemyway-kr** [comment]
원래 디비에서도 안됨 @unbroken2650 @intersoom

**Comment by suho-han** [comment]
?? aws 올라간건 잘 되던데
![image](https://user-images.githubusercontent.com/58286965/151700563-fc8ea590-c821-41aa-8a62-c3271d8498d4.png)

**Comment by makemyway-kr** [comment]
지금 sqlite브랜치에서 하니까 안돼

**Comment by suho-han** [comment]
> 지금 sqlite브랜치에서 하니까 안돼

그건 main에서 변경사항 반영 안 해서 그런거 아님??

**Comment by makemyway-kr** [comment]
아 그런가?

**Comment by makemyway-kr** [comment]
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/58161987/151702344-e0ac23c6-3a86-4084-a216-59ff087145fb.png">
lockerlist페이지에서부터 session storage로 사물함 번호가 한글로 되어있어서 그걸 받아서 전달하는 과정에서도 한글로 된듯.

**Comment by makemyway-kr** [comment]
@unbroken2650
