### ISSUE TITLE
메인화면 수정pr

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/lockerweb#80]
한번만 다시 체크해보구 PR다시 올려주라 REVERT해서 PR안되넵
https://mmozzi.tistory.com/83
여기서는 url뒤에 ?after추가해보라는데

**Comment by suho-han** [comment]
ㅇㅋ 일단 해볼게

**Comment by makemyway-kr** [comment]
해봤나유?

**Comment by suho-han** [comment]
무슨 브랜치인지 알려줘

**Comment by suho-han** [comment]
일단 sqlite에서 할게
