### ISSUE TITLE
OperationlError: no such column: locker_department.fintime

### ISSUE THREAD

**Issue by suho-han** [amuguna1mandeum/lockerweb#81]
![image](https://user-images.githubusercontent.com/58286965/156366471-b2627444-5b6c-49e5-9ae4-e30c1c5ff501.png)

확인해주세요.

**Comment by makemyway-kr** [comment]
Sqlite에서한거?


나의 iPad에서 보냄

**Comment by makemyway-kr** [comment]
Column이 없다는건 너가 migrate안해서 그럼.
Migrate하셈

**Comment by suho-han** [comment]
했는데도 저렇게 떠

**Comment by makemyway-kr** [comment]
저거 sqlite디비 브라우저 들어가서 fintime column있는지 봐바

**Comment by makemyway-kr** [comment]
makemigrations랑 migrate하니까 잘 됨 ㅡㅡ 해서 올려놨다. @unbroken2650

**Comment by suho-han** [comment]
https://araikuma.tistory.com/686
안 되길래 콘솔로 column 추가함
