### ISSUE TITLE
취소시 표시오류

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/lockerweb#85]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/58161987/157236936-0c1be40d-fc13-40a6-9c3e-d5a034d6df8d.png">

**Comment by makemyway-kr** [comment]
Code filter함수 수정으로 해결완료

**Comment by suho-han** [comment]
![image](https://user-images.githubusercontent.com/58286965/157424550-e572cf12-9f52-4b6c-97e1-2f1c9e74efe1.png)

![image](https://user-images.githubusercontent.com/58286965/157424535-a1151abd-e7ca-4f8d-8e1a-8994fe95009f.png)
전체 다 안 감싸져 있었음.

**Comment by suho-han** [comment]
![image](https://user-images.githubusercontent.com/58286965/157425058-02fcd363-91d0-468f-b11c-f43e8b0dd930.png)
현재는 복구 완료.
